#################################################################
# Network
#################################################################
networks:
  pg-net:
    driver: bridge

#################################################################
# Volumes
#################################################################
volumes:
  pg-data:

#################################################################
# Services
#################################################################
services:
  postgres:
    container_name: pgautoupgrade-db
    image: pgautoupgrade/pgautoupgrade:18.1-alpine
    restart: unless-stopped

    networks:
      - pg-net

    #############################################################
    # Environment variables from .env file
    #############################################################
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    #############################################################
    # Ports
    #############################################################
    ports:
      - "5432:5432"

    #############################################################
    # Persistent Storage
    #############################################################
    volumes:
      - pg-data:/var/lib/postgresql/data

    #############################################################
    # Optional sysctls (security/hardening)
    #############################################################
    # sysctls:
    #   net.ipv4.tcp_syncookies: 1
    #   net.ipv4.ip_forward: 0
#################################################################
# End of Compose
#################################################################
